name: nucleosome_sim
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - biopython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - brokenaxes
  - numba
  - tqdm
  - scikit-learn
  - statsmodels
  - psutil
  - cython
  - pip:
      - pipdeptree
      - line_profiler