#!/bin/bash
# ----------------SLURM Parameters----------------
#SBATCH -p all.q
#SBATCH -n 15
#SBATCH --mem-per-cpu=1G
#SBATCH -N 1
#SBATCH --mail-type=ALL
#SBATCH -J GC_profiling
#SBATCH -D /home/pol_schiessel/maya620d/Genome_Signal_Analysis/GC_Profiling
#SBATCH --output=Array_eukaryote.%A_%a.out
#SBATCH --error=Array_eukaryote.%A_%a.error
#SBATCH -A undefined
#SBATCH --array=1-10%10
### Submit 2 tasks with task ID 1,2. Run max 2 tasks concurrently
# ----------------Load Modules--------------------
#module load apps/biopython/1.79
module load apps/python3/3.9.5


#------------------Get Arguments and Create Directory--------
param_store=param_file.txt


# Get first argument
param_id=$(cat $param_store | awk -F ',' -v var=$SLURM_ARRAY_TASK_ID 'NR==var {print $1}')
# Get second argument
ku=$(cat $param_store | awk -F ',' -v var=$SLURM_ARRAY_TASK_ID 'NR==var {print $2}')

# Get third argument
kw=$(cat $param_store | awk -F ',' -v var=$SLURM_ARRAY_TASK_ID 'NR==var {print $3}')

# Get third argument
ka=$(cat $param_store | awk -F ',' -v var=$SLURM_ARRAY_TASK_ID 'NR==var {print $4}')

# Get third argument
kd=$(cat $param_store | awk -F ',' -v var=$SLURM_ARRAY_TASK_ID 'NR==var {print $5}')

echo $param_id
echo $ku
echo $kw
echo $ka
echo $kd

# ----------------Commands------------------------
mkdir -p /group/pol_schiessel/05_Projekte/manish/Spermatogensis/results/

python3 main.py $param_id $ku $kw $ka $kd &&
echo Simulation done for $param_id $ku $kw $ka $kd parameters