# =============================================================================
# Config: ctrl02_random_genome_gcmatched
# Dataset: Random genome-wide sequences GC-matched to retained nucleosomes
# =============================================================================

DATASET_NAME="ctrl02_random_genome_gcmatched"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ctrl02_random_genome_gcmatched"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ctrl02_random_genome_gcmatched"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="24:00:00"
