# =============================================================================
# Config: ctrl05_unbound_prom_random
# Dataset: Unbound-promoter random nucleosomes
# =============================================================================

DATASET_NAME="ctrl05_unbound_prom_random"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ctrl05_unbound_prom_random"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ctrl05_unbound_prom_random"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="24:00:00"
