# =============================================================================
# Config: ctrl04_bound_prom_evicted
# Dataset: Bound-promoter evicted nucleosomes
# =============================================================================

DATASET_NAME="ctrl04_bound_prom_evicted"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ctrl04_bound_prom_evicted"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ctrl04_bound_prom_evicted"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="24:00:00"
