# =============================================================================
# Config: ctrl01_random_genome_safe
# Dataset: 20k random genome-wide safe 147-bp sequences
# =============================================================================

DATASET_NAME="ctrl01_random_genome_safe"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ctrl01_random_genome_safe"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ctrl01_random_genome_safe"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="24:00:00"
