# =============================================================================
# Config: ret_intermediate_nuc
# Dataset: Intermediate retained nucleosome positions (Hammoud et al.)
# =============================================================================

DATASET_NAME="ret_intermediate_nuc"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ret_intermediate_nuc"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ret_intermediate_nuc"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="48:00:00"
