# =============================================================================
# Config: ret_single_nuc
# Dataset: Single retained nucleosome positions (Hammoud et al., dyad ±73 bp)
# =============================================================================

DATASET_NAME="ret_single_nuc"
SPRM_DATASET_DIR="/group/pol_schiessel/Manish/Spermatogensis/SPRM_data/ret_single_nuc"
MARKOV_STORAGE_DIR="/group/pol_schiessel/Manish/Spermatogensis/markov_output/ret_single_nuc"

# ---- SLURM resources --------------------------------------------------------
SLURM_NTASKS=20
SLURM_MEM_PER_CPU="1G"
SLURM_TMP="5G"
SLURM_TIME="48:00:00"
