import sys
import os
sys.argv[1]
Param_ind = int(sys.argv[1])
NUC_BIND = 14
K_UNWRAP = float(sys.argv[2]) # 4
K_WRAP = float(sys.argv[3]) # 21
K_ADS = float(sys.argv[4]) # 2
K_DES = float(sys.argv[5]) # 23
P_CONC = float(sys.argv[6]) # in micro molar
COOPERATIVITY = float(sys.argv[7]) # KT
N_Independent_nucleosomes = 1000 ## Number of nucleosomes to run for the simulation, independently

Simulation_steps = 1000
System_Nucleosomes = 1 ### Number of nuclesomes to include in a single simulation. Right now we do Mono nucleosomes, later need to increase to multiple nucleosomes with cooperativity effect among nucleosomes.

SEQ_id = float(sys.argv[8])
# SEQUENCE = 'ATCAATATCCACCTGCAGATACTACCAAAAGTGTATTTGGAAACTGCTCCATCAAAAGGCATGTTCAGCTGGAATCCAGCTGAACATGCCTTTTGATGGAGCAGTTTCCAAATACACTTTTGGTAGTATCTGCAGGTGGATATTGAT'
# SEQUENCE = 'GGCCCGATACTGTATGAGCATACAGTACAGACGATATCGGGCACTTTCAGGGTGGTATGGCCGTAGGCGAGCACAAGGCTGACTTTTCCTCCCCTTGTGCTGCCTTCTGGGGGGGGCCCAGCCGGATCCCCGGGCGAGCTCGAATT' ### 5SL sequence from X.borealis with lexA at 8-27

# SEQUENCE = 'GGCCCGACCCTGCTTGGCTGCAGAGATCAGACGATATCGGGCACTTTCAGGGTGGTATGGCCGTAGGCGAGCACAAGGCTGACTTTTCCTCCCCTTGTGCTGCCTTCTGGGGGGGGCCCAGCCGGATCCCCGGGCGAGCTCGAATT' ### 5S sequence from X.borealis

SEQUENCE = 'CTGGAGAATCCCGGTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT' ### 601 sequences
# SEQUENCE = 'AT'*73+'A' 

# SEQUENCE = 'TCCAGGGATTTATAAGCCGATGACGTCATAACATCCCTGACCCTTTAAATAGCTTAACTTTCATCAAGCAAGAGCCTACGACCATACCATGCTGAATATACCGGTTCTCGTCCGATCACCGAAGTCAAGCAGCATAGGGCTCGGTT'  ### 5S sequence from Sea urchin


# SEQUENCE = 'GC'*73 + 'G'

# SEQUENCE = str(sys.argv[9])


# SEQUENCE = 'GTGCCGAGGCCGCTCAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGTCTGGAGAATCCCG'


# 'CTGGAGATACTGTATGAGCATACAGTACAATTGGTCGTAGACAGCTCTAGCACCGCTTAAACGCACGTACGCGCTGTCCCCCGCGTTTTAACCGCCAAGGGGATTACTCCCTAGTCTCCAGGCACGTGTCAGATATATACATCCTGT' ### 601 L sequence with LEXA at 8-27 (TACTGTATGAGCATACAGTA)

# AATTCCAACGAATAACTTCCAGGGATTTATAAGCCGATGACGTCATAACATCCCTGACCC
#     GGTTGCTTATTGAAGGTCCCTAAATATTCGGCTACTGCAGTATTGTAGGGACTGGG

# TTTAAATAGCTTAACTTTCATCAAGCAAGAGCCTACGACCATACCATGCTGAATATACCG
# AAATTTATCGAATTGAAAGTAGTTCGTTCTCGGATGCTGGTATGGTACGACTTATATGGC

# GTTCTCGTCCGATCACCGAAGTCAAGCAGCATAGGGCTCGGTTAGTACTTGGATGGGAGA
# CAAGAGCAGGCTAGTGGCTTCAGTTCGTCGTATCCCGAGCCAATCATGAACCTACCCTCT

# CCGCCTGGGAATACCGGGTGTTGTAGGCTTTTTTTTCTCCCCCCCCCCCCTCTTTGCTTC
# GGCGGACCCTTATGGCCCACAACATCCGAAAAAAAAGAGGGGGGGGGGGGAGAAACGAAG

# ATGAAATGCCTCTTGG
# TACTTTACGGAGAACCTTAA


               #
# AATTCCAACGAATAACT  AGTACTTGGATGGGAGACCGCCTGGGAATACCGGGTGTTGTAGGCTTTTTTTTCTCCCCCCCCCCCCTCTTTGCTTCATGAAATGCCTCTTGG





RESULT_DIR = r"C:\Users\maya620d\PycharmProjects\Spermatogensis\results\/"

MD_param_loc = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\MD_stiffness.csv'
Olson_prob_di_loc = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\Olson_RoomTemp_dinucdist.csv'
Olson_prob_tri_loc = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\Olson_RoomTemp_trinucdist.csv'
Olson_prob_mono_loc = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\Olson_RoomTemp_nucdist.csv'
SAXS_loc = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\SAXS_fraction.csv'

SAXS_DIST = r'C:\Users\maya620d\PycharmProjects\Spermatogensis\Parameters\601_stationary_dist.txt'